// Mocks generated by Mockito 5.2.0 from annotations
// in flutter_bloc_architecture/test/bloc/news_cubit_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:flutter_bloc_architecture/src/models/article.dart' as _i4;
import 'package:flutter_bloc_architecture/src/repository/news_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [NewsRepositoryBase].
///
/// See the documentation for Mockito's code generation for more information.
class MockNewsRepositoryBase extends _i1.Mock
    implements _i2.NewsRepositoryBase {
  MockNewsRepositoryBase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Article>> fetchTopHeadlines(String? country) =>
      (super.noSuchMethod(Invocation.method(#fetchTopHeadlines, [country]),
              returnValue: Future<List<_i4.Article>>.value(<_i4.Article>[]))
          as _i3.Future<List<_i4.Article>>);
}
